[package]
name = "citesync"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
name = "libcitesync"
path = "lib/main.rs"

[[bin]]
name = "citesync"
path = "client/main.rs"

[[bin]]
name = "citesync-server"
path = "server/main.rs"

[dependencies]
atom_syndication = "0.12.7"
biblatex = "0.10.0"
clap = { version = "4.5.40", features = ["suggestions", "color", "cargo", "derive", "env"] }
color-eyre = "0.6.5"
confy = "1.0.0"
directories-next = "2.0.0"
eyre = "0.6.12"
glob = "0.3.2"
mime = "0.3.17"
mime_guess = "2.0.5"
poem = "3.1.11"
poem-openapi = { version = "5.1.15", features = ["swagger-ui"] }
ratatui = "0.29.0"
rayon = "1.10.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_derive = "1.0.219"
serde_json = "1.0.141"
sqlx = { version = "0.8.6", features = ["runtime-tokio", "sqlite"] }
strum = "0.27.1"
strum_macros = "0.27.1"
tokio = { version = "1.45.1", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
uuid = { version = "1.17.0", features = ["v4"] }
